version: "3.9"

services:
  aggregator:
    build:
      context: services
      dockerfile: aggregator-dockerfile
    container_name: aggregator
    ports:
      - "80:9989"
    environment:
      - MICRONAUT_ENVIRONMENTS=dev
    networks:
      - eposeanet

networks:
  eposeanet:
    name: eposea_network
